### PR TITLE
Fix auth missing from session after first login

### LINKED ISSUE #26: Index page shown right after login is sometimes incorrect
Sometimes right after logging into the website, the user is shown the "unauthed" home page rather than the "authed" homepage.

### PR DESCRIPTION
**Pull request by justinrusso**
Seems like there was a race condition happening here. We can use `.save` on session to ensure that the information is saved into the database before continuing to redirect to the home page.

Fixes #26

### CODE REVIEW

File: auth.js [hunk 1]
```diff
@@ -1,6 +1,7 @@
 const { User } = require("./db/models");
 
 const restoreUser = async (req, res, next) => {
+  console.log(req.session);
```
Comment (kvh8899) [inline auth.js]: This can be deleted

**Review by kvh8899 — APPROVED** [review]
